version: '3'
services:
  minecraft-server:
    image: "itzg/minecraft-server:multiarch"
    container_name: "mc-pi"
  
    ports:
      #- "25575:25575"
      - "25565:25565"
      - "4711:4711"
  
    volumes:
      - "./data:/data"
      - "./plugins:/plugins"
  
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.8-R0.1-SNAPSHOT-latest"
  
    tty: true
    stdin_open: true
  jupyter:
    build:
      context: ./jupyter
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 9999:8888
    volumes:
      - ./jupyter:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='password'
  

